version: '3.8'
services:
  rest-api:
    build: .
    ports:
      - '3000:3000'
    hostname: listwibuku-rest-service
    volumes:
      - ./:/app
    environment:
      DB_NAME: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: pgpassword
      DB_HOST: host.docker.internal
      DB_PORT: 5433
      PORT: 3000
      SOAP_API_KEY: 1MHJG1a7gQZWjR1YShD2D5DUU2hQ7HLkUSnLbXULDw08iBHbLApMV4AZAR3V
      SOAP_SERVICE_URL: http://host.docker.internal:3001/subscriberservice
    depends_on:
      - postgresql
  postgresql:
    image: postgres:14-alpine
    ports:
      - '5433:5432'
    hostname: listwibuku-rest-database
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pgpassword}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
volumes:
  postgres:
